M48
; DRILL file {KiCad 7.0.1} date Mon Sep  4 23:27:28 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-09-04T23:27:28+05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X162.7Y-69.145
X162.7Y-73.995
T2
X165.73Y-68.845
X165.73Y-74.295
T3
X98.66Y-53.21
X98.66Y-127.51
X155.06Y-53.21
X155.06Y-127.51
T0
M30
